version: '3.9'

services:
 db:
  image: postgres:14.1-alpine
  restart: unless-stopped
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
  ports:
   - '5432:5432'
  volumes:
   - db:/var/lib/postgresql/data

 pgadmin:
  image: dpage/pgadmin4
  restart: unless-stopped
  ports:
   - '5050:80'
  environment:
   PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.pgadmin
   PGADMIN_DEFAULT_PASSWORD: pgadmin123
  volumes:
   - pgadmin-data:/var/lib/pgadmin

 # minio:
 #  image: minio/minio:latest
 #  entrypoint: sh
 #  restart: unless-stopped
 #  ports:
 #   - '9000:9000'
 #   - '9001:9001'
 #  command: -c 'minio server --console-address ":9001" /data'
 #  environment:
 #   MINIO_ROOT_USER: minio
 #   MINIO_ROOT_PASSWORD: minio123
 #  volumes:
 #   - minio-data:/data
 #  healthcheck:
 #   test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
 #   interval: 30s
 #   timeout: 20s
 #   retries: 3
 #
 # createbuckets:
 #  image: minio/mc
 #  depends_on:
 #   - minio
 #  entrypoint: >
 #   /bin/sh -c "
 #   /usr/bin/mc alias set myminio http://minio:9000 minio minio123;
 #   /usr/bin/mc mb myminio/images;
 #   /usr/bin/mc anonymous set public myminio/images;
 #   exit 0;
 #   "
 #
volumes:
 pgadmin-data:
 # minio-data:
 db:
