import type { Metadata, Viewport } from 'next'
import { Nunito } from 'next/font/google'
import './globals.css'
import AppProvider from './_providers/appPrivider'
import { getAppSessionServer } from '@front/kernel/lib/next-auth/getAppSessionServer'
import { ThemeSwither } from '@front/kernel/lib/next-theme/themeSwither'

const nunito = Nunito({
	subsets: ['cyrillic'],
	variable: '--font-sans',
	weight: ['400', '600', '700']
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export const viewport: Viewport = {
	width: 'device-width',
	initialScale: 1,
	themeColor: 'auto'
}

export default async function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	const session = await getAppSessionServer()

	return (
		<html lang="ru">
			<body className={nunito.className}>
				<AppProvider session={session}>
					{children}
					<footer>
						<ThemeSwither />
					</footer>
				</AppProvider>
			</body>
		</html>
	)
}
