name: deploy

on:
 push:
  branches:
   - main

jobs:
 deploy:
  runs-on: ubuntu-latest
  concurrency:
   group: staging
   cancel-in-progress: true
  steps:
   - name: SSH Command
     uses: D3rHase/ssh-command-action@v0.2.2
     with:
      host: ${{ secrets.STAGING_SSH_HOST }}
      user: ${{ secrets.STAGING_SSH_USERNAME }}
      private_key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
      host_fingerprint: ${{ secrets.STAGING_SSH_FINGERPRINT }}
      command: source ~/.nvm/nvm.sh; echo 'hello '
